---
galaxy_info:
  author: Ironic Developers
  description: Create VM nodes for local Bifrost testing.
  company: OpenStack
  license: Apache
  min_ansible_version: 1.9
  platforms:
  - name: EL
    versions:
    - 8
  - name: Debian
    versions:
    - stretch
    - buster
  - name: Ubuntu
    versions:
    - xenial
    - bionic
  categories:
  - cloud
  - cloud:openstack
dependencies: []
