---
galaxy_info:
  author: Ironic Developers
  description: Creates a basic configdrive for Bifrost
  company: OpenStack
  license: Apache
  min_ansible_version: 2.0
  platforms:
  - name: EL
    versions:
    - 8
  - name: Ubuntu
    versions:
    - xenial
    - bionic
  - name: Debian
    versions:
    - stretch
    - buster
  categories:
  - cloud
  - cloud:openstack
dependencies: []
