# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or
# implied.
# See the License for the specific language governing permissions and
# limitations under the License.
---
- name: "Check that the provided interface is defined"
  fail:
    msg: >
      Network interface {{ network_interface }} is not known to Ansible.
      If you're testing Bifrost on virtual machines, do not forget to invoke
      "bifrost-cli testenv" or use the "bifrost-create-vm-nodes" role first.
      If you're using Bifrost on real bare metal, you have to provide the
      network interface via the "network_interface" variable or the
      --network-interface argument to "bifrost-cli install".
  when: ('ansible_' + ans_network_interface) not in hostvars[inventory_hostname]

# NOTE(cinerama) dummy-defaults.yml is an empty defaults file. We use it
# here to ensure that with_first_found won't fail should we not have
# defaults for a particular distribution, version, etc.
- name: Include OS family-specific defaults
  include_vars: "{{ item }}"
  with_first_found:
    - "../defaults/required_defaults_{{ ansible_os_family }}_family.yml"
    - "../defaults/dummy-defaults.yml"

- name: Include OS distribution-specific defaults
  include_vars: "{{ item }}"
  with_first_found:
    - "../defaults/required_defaults_{{ ansible_distribution }}.yml"
    - "../defaults/dummy-defaults.yml"

- name: Include OS version-specific defaults
  include_vars: "{{ item }}"
  with_first_found:
    - "../defaults/required_defaults_{{ ansible_distribution }}_{{ ansible_distribution_release }}.yml"
    - "../defaults/required_defaults_{{ ansible_distribution }}_{{ ansible_distribution_version }}.yml"
    - "../defaults/dummy-defaults.yml"

- name: "Install Keystone"
  include: install.yml
  when:
    - enable_keystone | bool
    - not skip_package_install | bool

- name: "Bootstrap Keystone"
  include: bootstrap.yml
  when:
    - enable_keystone | bool
    - not skip_bootstrap | bool

- name: "Upgrade existing installation"
  include: upgrade.yml
  when:
    - enable_keystone | bool
    - not skip_bootstrap | bool
    - not skip_start | bool

- name: "Start Keystone services"
  include: start.yml
  when:
    - enable_keystone | bool
    - not skip_start | bool
